version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - ENABLE_IP_LIMITER=true
      - IP_LIMIT=5
      - IP_EXPIRATION=300
      - ENABLE_TOKEN_LIMITER=true
      - TOKEN_LIMIT=10
      - TOKEN_EXPIRATION=300
    depends_on:
      - redis

volumes:
  redis_data: